[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/youpie/dotenvy.git"]
git = "https://github.com/youpie/dotenvy.git"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
